[package]
name = "mxc_service"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mxc-service"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
mxc_service_proto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
ciborium = { workspace = true }
mxc_service_rpc_server = { workspace = true }
mxc_wfp = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Pipes",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_NetworkManagement_WindowsFirewall",
    "Win32_System_Rpc",
    "Win32_System_Services",
    "Win32_Security_WinTrust",
    "Win32_Security_Cryptography",
    "Win32_Security_Cryptography_Catalog",
    "Win32_Security_Cryptography_Sip",
] }
windows-core = { workspace = true }
windows-service = { workspace = true }
ctrlc = { workspace = true }
