steps:
  - pwsh: |
      $cfg = "$(Build.SourcesDirectory)/.cargo/config.toml"
      New-Item -ItemType Directory -Force -Path (Split-Path $cfg) | Out-Null
      Add-Content -Path $cfg -Value ("`n" + (Get-Content -Raw "$(Build.SourcesDirectory)/.azure-pipelines/.cargo/config.toml"))
    displayName: Setup Cargo Config

  - task: CargoAuthenticate@0
    displayName: Cargo Authenticate
    inputs:
      configFile: $(Build.SourcesDirectory)/.cargo/config.toml
