parameters:
- name: targetTriple
  type: string
- name: workingDirectory
  type: string
- name: cargoArgs
  type: string
  default: ''
- name: enableTest
  type: string
  default: 'true'
- name: rustVersion
  type: string
  default: '1.93'

steps:
  - template: Rust.Toolchain.Public.yml@self
    parameters:
      targetTriple: ${{ parameters.targetTriple }}
      rustVersion: ${{ parameters.rustVersion }}

  - template: Cargo.Setup.Public.yml@self

  - task: Cache@2
    displayName: Cache cargo target directory
    inputs:
      key: 'cargo-target | "$(Agent.OS)" | "${{ parameters.targetTriple }}" | src/Cargo.lock'
      restoreKeys: |
        cargo-target | "$(Agent.OS)" | "${{ parameters.targetTriple }}"
      path: $(CARGO_TARGET_DIR)

  - script: cargo build --locked --release --target ${{ parameters.targetTriple }} ${{ parameters.cargoArgs }}
    displayName: Build
    workingDirectory: ${{ parameters.workingDirectory }}

  - script: cargo test --locked --release --target ${{ parameters.targetTriple }} ${{ parameters.cargoArgs }}
    displayName: Test
    workingDirectory: ${{ parameters.workingDirectory }}
    condition: eq('${{ parameters.enableTest }}', 'true')
