[package]
name = "mxc_service_client"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "mxc-net"
path = "src/bin/mxc-net.rs"

[dependencies]
clap = { workspace = true }
mxc_service_proto = { workspace = true }
mxc_service_rpc_client = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
ciborium = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Services",
] }
